[webservers]

web-1 ansible_host=10.0.1.4 fqdn=fhmfnlsj8p7n2nqd75f4.auto.internal

web-2 ansible_host=10.0.1.34 fqdn=fhm42t7g5qdlfann022s.auto.internal


[databases]

main ansible_host=10.0.1.21 fqdn=fhmfieuf26tfopqfofsb.auto.internal

replica ansible_host=10.0.1.19 fqdn=fhm8c002aeqj1jc3t2ji.auto.internal


[storage]

storage ansible_host=10.0.1.17 fqdn=fhmjtjgtee0t0srbdetc.auto.internal
