[webservers]

web-1 ansible_host=10.0.1.36 fqdn=fhmtgmqevkeiavtdpo6e.auto.internal

web-2 ansible_host=10.0.1.8 fqdn=fhmamu5l6pn7mgqe5vum.auto.internal


[databases]

main ansible_host=10.0.1.15 fqdn=fhmn5te39pnnvgt2o8ij.auto.internal

replica ansible_host=10.0.1.20 fqdn=fhmsl18qv7a2ecprtk5m.auto.internal


[storage]

storage ansible_host=10.0.1.27 fqdn=fhmflfipnmtom72l1mb1.auto.internal
